export const ROUTING_PERMISSION = {
  //user permissions
  UPDATE_USER: 'UPDATE-USER',
  VIEW_USER: 'VIEW-USER',
  ADD_USER: 'ADD-USER',
  DELETE_USER: 'DELETE-USER',
  LIST_USER: 'LIST-USER',

  //site permissions
  UPDATE_SITE: 'UPDATE-SITE',
  VIEW_SITE: 'VIEW-SITE',
  ADD_SITE: 'ADD-SITE',
  DELETE_SITE: 'DELETE-SITE',
  LIST_SITE: 'LIST-SITE',

  //Staff permissions
  UPDATE_STAFF: 'UPDATE-STAFF',
  VIEW_STAFF: 'VIEW-STAFF',
  ADD_STAFF: 'ADD-STAFF',
  DELETE_STAFF: 'DELETE-STAFF',
  LIST_STAFF: 'LIST-STAFF',

  //device permissions
  UPDATE_DEVICE: 'UPDATE-DEVICE',
  VIEW_DEVICE: 'VIEW-DEVICE',
  ADD_DEVICE: 'ADD-DEVICE',
  DELETE_DEVICE: 'DELETE-DEVICE',
  LIST_DEVICE: 'LIST-DEVICE',

  //room permissions
  UPDATE_ROOM: 'UPDATE-ROOM',
  VIEW_ROOM: 'VIEW-ROOM',
  ADD_ROOM: 'ADD-ROOM',
  DELETE_ROOM: 'DELETE-ROOM',
  LIST_ROOM: 'LIST-ROOM',
};
